const CommitLintScopes = [
	'CommitLint Config',
	'ESLint Config',
	'Jest Config',
	'Prettier Config',
	'Root Directory',
	'Semantic Release Config',
	'StyleLint Config',
	'TypeScript Config',
	'Vitest Config',
]

const CommitLintTypes = [
	'♿️ A11y',
	'➕ Add Dependencies',
	'🧪 Add Test',
	'🔬 Analytics',
	'💥 Breaking Change',
	'📦 Build',
	'♻️ Chore',
	'⚙️ CI',
	'👁️‍🗨️ Code Review',
	'🔧 Config',
	'💄 Cosmetic',
	'🚀 Deploy',
	'💡 Document Source Code',
	'📖 Docs',
	'⬇️ Downgrade Dependencies',
	'✨ Feature',
	'🐛 Fix',
	'🎨 Format',
	'⚡️ General Update',
	'🚑 Hotfix',
	'🎉 Initial',
	'👚 Lint',
	'🐧 Linux Fix',
	'🍎 MacOS Fix',
	'✅ Make Test Pass',
	'🔀 Merge Branches',
	'📇 Metadata',
	'🚚 Move/Rename Repository',
	'🐎 Performance',
	'🔨 Refactor',
	'➖ Remove Dependencies',
	'🗑️ Revert',
	'🔒 Security',
	'💎 Style',
	'🚨 Tests',
	'🔤 Translate',
	'⬆️ Upgrade Dependencies',
	'🔖 Version Tag',
	'🪟 Windows Fix',
	'🚧 WIP',
]

export { CommitLintScopes, CommitLintTypes}
