blank_issues_enabled: false
contact_links:
  - name: The Design System Community Support
    url: https://github.com/emsim11/The-Design-System/discussions
    about: Please ask and answer questions here.
